#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Install/apply Nazar's Basm terminal font locally.
#
# Basm uses display/pixel fonts for web labels, but the daily terminal needs a
# readable monospace. CozetteVector is the default: compact, local, and works
# in Kitty. Departure Mono and JetBrains Mono remain available as alternatives
# for people who prefer a different texture.
set -euo pipefail

DIR="${NAZAR_DIR:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}"
FONT_DST="${XDG_DATA_HOME:-$HOME/.local/share}/fonts/nazar"
KITTY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
KITTY_CONF="$KITTY_DIR/kitty.conf"
KITTY_NAZAR_CONF="$KITTY_DIR/nazar.conf"
FONT_FAMILY="${NAZAR_TERMINAL_FONT:-Cozette}"
FONT_SIZE="${NAZAR_TERMINAL_FONT_SIZE:-}"

mkdir -p "$FONT_DST" "$KITTY_DIR"

install_cozette() {
  local src="$DIR/assets/fonts/cozette/CozetteVector.ttf"
  [ -f "$src" ] || { echo "Missing Cozette asset: $src" >&2; exit 1; }
  cp -f "$src" "$FONT_DST/"
}

install_departure_mono() {
  local src="$DIR/assets/fonts/departure-mono/DepartureMono-Regular.otf"
  [ -f "$src" ] || { echo "Missing Departure Mono asset: $src" >&2; exit 1; }
  cp -f "$src" "$FONT_DST/"
}

install_jetbrains_mono() {
  local src_dir="$DIR/web/fonts"
  shopt -s nullglob
  local fonts=("$src_dir"/jetbrainsmono-*.woff2)
  [ "${#fonts[@]}" -gt 0 ] || { echo "No JetBrains Mono font files found in $src_dir" >&2; exit 1; }
  cp -f "${fonts[@]}" "$FONT_DST/"
}

case "${FONT_FAMILY,,}" in
  cozette|cozettevector|cozette-vector)
    FONT_FAMILY="CozetteVector"
    install_cozette
    [ -n "$FONT_SIZE" ] || FONT_SIZE="13.0"
    ;;
  "departure mono"|departure|departure-mono)
    FONT_FAMILY="Departure Mono"
    install_departure_mono
    [ -n "$FONT_SIZE" ] || FONT_SIZE="11.0"
    ;;
  "jetbrains mono"|jetbrains|jetbrains-mono)
    FONT_FAMILY="JetBrains Mono"
    install_jetbrains_mono
    [ -n "$FONT_SIZE" ] || FONT_SIZE="11.0"
    ;;
  *)
    echo "Unknown NAZAR_TERMINAL_FONT='$FONT_FAMILY'. Use 'Cozette', 'Departure Mono', or 'JetBrains Mono'." >&2
    exit 1
    ;;
esac

if command -v fc-cache >/dev/null 2>&1; then
  fc-cache -f "$FONT_DST" >/dev/null 2>&1 || fc-cache -f >/dev/null 2>&1 || true
fi

cat > "$KITTY_NAZAR_CONF" <<EOF
# Nazar / Basm terminal font.
# Generated by scripts/install-basm-terminal-fonts.sh.
# Remove this include from kitty.conf to revert.
font_family      $FONT_FAMILY
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        $FONT_SIZE
# Keep ligatures available but do not rely on them for Nazar's UI geometry.
disable_ligatures never
EOF

if [ ! -f "$KITTY_CONF" ]; then
  cat > "$KITTY_CONF" <<EOF
# Kitty config created by Nazar.
include $KITTY_NAZAR_CONF
EOF
elif ! grep -Fq "include $KITTY_NAZAR_CONF" "$KITTY_CONF"; then
  {
    printf '\n# Nazar / Basm terminal font\n'
    printf 'include %s\n' "$KITTY_NAZAR_CONF"
  } >> "$KITTY_CONF"
fi

printf 'Installed %s to %s\n' "$FONT_FAMILY" "$FONT_DST"
if command -v fc-match >/dev/null 2>&1; then
  printf 'fontconfig match: '
  fc-match "$FONT_FAMILY" || true
fi
printf 'Wrote Kitty font config: %s\n' "$KITTY_NAZAR_CONF"
printf 'Kitty includes it from: %s\n' "$KITTY_CONF"
printf 'Open a new Kitty window, or reload Kitty config (Ctrl+Shift+F5) to apply.\n'
